apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.deployment.appName }}
    hpe-ezua/type: vendor-service
    hpe-ezua/app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: {{ .Values.deployment.appName }}
