apiVersion: v1
kind: Service
metadata:
  name: {{ include "sqlhandler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sqlhandler.labels" . | nindent 4 }}
    {{- include "sqlhandler.ezua.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "sqlhandler.selectorLabels" . | nindent 4 }}
