{{- if and .Values.sharedContent .Values.sharedContent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-shared-content
  namespace: {{ .Release.Namespace }}
  labels:
    hpe-ezua/type: vendor-service
    hpe-ezua/app: {{ .Chart.Name }}
data:
{{- range $path, $content := .Files.Glob "shared/**" }}
  {{- if not (hasPrefix "." (base $path)) }}
  {{- $key := trimPrefix "shared/" $path | replace "/" "." }}
  {{ $key }}: |
{{ $content | toString | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
