apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shared-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    hpe-ezua/type: vendor-service
    hpe-ezua/app: {{ .Chart.Name }}
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.sharedSize }}
