apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    hpe-ezua/type: vendor-service
    hpe-ezua/app: {{ .Chart.Name }}
type: Opaque
stringData:
  OPENCODE_SERVER_USERNAME: {{ .Values.auth.username }}
  OPENCODE_SERVER_PASSWORD: {{ .Values.auth.password }}
  SESSION_SECRET: {{ .Values.sessionSecret }}
  ADMIN_USERNAME: {{ .Values.admin.username }}
  ADMIN_PASSWORD: {{ .Values.admin.password }}
