apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "model-downloader.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "model-downloader.labels" . | nindent 4 }}
