apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: {{ .Release.Namespace }}
  labels:
    hpe-ezua/type: vendor-service
    hpe-ezua/app: {{ .Chart.Name }}
spec:
  hosts:
  - {{ .Values.ezua.virtualService.endpoint }}
  gateways:
  - {{ .Values.ezua.virtualService.istioGateway }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Release.Name }}-svc.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
